"""Create initial tables for unsubscribed_emails and logs

Revision ID: 3ad96ef9cbde
Revises:
Create Date: 2025-06-10 05:33:19.364111

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ad96ef9cbde"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_app", sa.String(), nullable=False),
        sa.Column("log_level", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("details_json", sa.JSON(), nullable=True),
        sa.Column("inserted_by", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_logs_id"), "logs", ["id"], unique=False)
    op.create_index(op.f("ix_logs_timestamp"), "logs", ["timestamp"], unique=False)
    op.create_table(
        "unsubscribed_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sender_name", sa.String(), nullable=False),
        sa.Column("sender_email", sa.String(), nullable=False),
        sa.Column("unsub_method", sa.String(), nullable=False),
        sa.Column(
            "inserted_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "unsub_method IN ('direct_link', 'isp_level')", name="unsub_method_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unsubscribed_emails_id"), "unsubscribed_emails", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_unsubscribed_emails_sender_email"),
        "unsubscribed_emails",
        ["sender_email"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_unsubscribed_emails_sender_email"), table_name="unsubscribed_emails"
    )
    op.drop_index(op.f("ix_unsubscribed_emails_id"), table_name="unsubscribed_emails")
    op.drop_table("unsubscribed_emails")
    op.drop_index(op.f("ix_logs_timestamp"), table_name="logs")
    op.drop_index(op.f("ix_logs_id"), table_name="logs")
    op.drop_table("logs")
    # ### end Alembic commands ###
