"""add indexes for filtering

Revision ID: f7712e5e2ff4
Revises: 3ad96ef9cbde
Create Date: 2025-06-11 09:32:46.460313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7712e5e2ff4"
down_revision: Union[str, None] = "3ad96ef9cbde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_unsubscribed_emails_unsub_method",
        "unsubscribed_emails",
        ["unsub_method"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_unsubscribed_emails_unsub_method", table_name="unsubscribed_emails"
    )
    # ### end Alembic commands ###
